#!/bin/csh -f
# $1 - schema name, $2 - scope
set rig='~/rigal/rigsc.446/bin'
$rig/rc MP2-parser
$rig/ic MP2-parser -d $1 tree $2> temp.txt
$rig/rc MP2-generator
$rig/ic MP2-generator -d tree> temp2.txt
rm tree *.rsc
echo "C++ compiler: g++ $1.cpp -o $1 -fast"
time /Developer/usr/bin/g++ "$1.cpp" -o $1 -fast
echo "$1 run: ./$1>$1.txt"
time ./$1>"$1.txt"
echo "Completed $1 for scope $2"
rm $1 xd RIGCOMP.TMP 